[package]
name = "k-nearest-neighbors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rand = "0.8.5"
reqwest = "0.11.18"
tokio-test = "0.4.2"
