[package]
name = "k-nearest-neighbors"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
anyhow = "1.0.71"
rand = "0.8.5"
reqwest = "0.11.18"
tokio = { version = "1.29.1", features = ["macros"] }
tokio-test = "0.4.2"
